// <auto-generated />
using System;
using EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230305120903_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseStatusStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SeverityLevelLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeOfCaseClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOfCaseComment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeOfCaseOpen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseStatusStatus");

                    b.HasIndex("SeverityLevelLevel");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CaseStatusEntity", b =>
                {
                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Status"));

                    b.HasKey("Status");

                    b.ToTable("CaseStatus");
                });

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("char(13)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.SeverityLevelEntity", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Level"));

                    b.HasKey("Level");

                    b.ToTable("SeverityLevel");
                });

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CaseEntity", b =>
                {
                    b.HasOne("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CaseStatusEntity", "CaseStatus")
                        .WithMany()
                        .HasForeignKey("CaseStatusStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.SeverityLevelEntity", "SeverityLevel")
                        .WithMany()
                        .HasForeignKey("SeverityLevelLevel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseStatus");

                    b.Navigation("SeverityLevel");
                });

            modelBuilder.Entity("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CustomerEntity", b =>
                {
                    b.HasOne("EC05_C_sharp_EFC_DI_HOST_MVVM_WPF.MVVM.Models.Entities.CaseEntity", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });
#pragma warning restore 612, 618
        }
    }
}
